# Generated by Django 4.2.7 on 2023-12-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('library_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed_by',
            field=models.ManyToManyField(related_name='borrowed_books', through='library_ads.Borrow', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrowed_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
