# Generated by Django 4.2.7 on 2023-11-21 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='date_register',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='books',
            name='loan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
