# Generated by Django 4.2.7 on 2023-11-29 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='date_register',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='books',
            name='loan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
