# Generated by Django 4.2.7 on 2023-11-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_ads', '0002_books_borrowed_books_date_register_books_loan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='cod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
