# Generated by Django 4.2.7 on 2023-11-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_ads', '0003_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='date_returned',
        ),
    ]
