# Generated by Django 4.2.7 on 2023-11-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_ads', '0004_remove_borrow_date_borrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
