# Generated by Django 4.2.7 on 2023-11-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_ads', '0005_books_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='copies',
        ),
    ]
