# Generated by Django 4.2.7 on 2023-12-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_ads', '0006_remove_books_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrowed',
            field=models.IntegerField(),
        ),
    ]
